name: beats
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  dartz: ^0.10.1
  google_sign_in: ^6.1.0
  google_fonts: ^4.0.3
  extended_image: ^7.0.2
  animated_theme_switcher: ^2.0.8
  shimmer: ^2.0.0
  another_flushbar: ^1.12.29
  flutter_tags: 1.0.0-nullsafety.1
  textfield_tags: ^2.0.2
  collection: ^1.17.0
  file_picker: ^5.2.9
  flutter_animator: ^3.2.2
  rxdart: ^0.27.7
  uuid: ^3.0.7
  infinite_scroll_pagination: ^3.2.0
  auto_route: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5
  auto_route_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
