// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3i-FFafK7mueKm6ZtOEDCHuxzNgqk40',
    appId: '1:886145540803:web:a1818ae4548a02de2d7876',
    messagingSenderId: '886145540803',
    projectId: 'mvara-beats',
    authDomain: 'mvara-beats.firebaseapp.com',
    storageBucket: 'mvara-beats.appspot.com',
    measurementId: 'G-4LP3EW7HFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBajlvjNnJLVcOMF8Z39UnKOD8-mekOBbY',
    appId: '1:886145540803:android:7b9bac81cd4529b32d7876',
    messagingSenderId: '886145540803',
    projectId: 'mvara-beats',
    storageBucket: 'mvara-beats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_tmuIyuygYvJgxtXRSVd7bQWcXDGppAU',
    appId: '1:886145540803:ios:6587d2c896232f312d7876',
    messagingSenderId: '886145540803',
    projectId: 'mvara-beats',
    storageBucket: 'mvara-beats.appspot.com',
    iosClientId: '886145540803-fva14nhoq21snlstaurigmnsho9jl2f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.beats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_tmuIyuygYvJgxtXRSVd7bQWcXDGppAU',
    appId: '1:886145540803:ios:6587d2c896232f312d7876',
    messagingSenderId: '886145540803',
    projectId: 'mvara-beats',
    storageBucket: 'mvara-beats.appspot.com',
    iosClientId: '886145540803-fva14nhoq21snlstaurigmnsho9jl2f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.beats',
  );
}
